# Generated by Django 4.1.5 on 2023-01-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='category',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrela'), ('GALAXIA', 'Palaxia'), ('PLANETA', 'Planeta')], default='', max_length=100),
        ),
    ]
