# Generated by Django 4.1.5 on 2023-01-15 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0004_fotografia_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='date_photo',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
