# Generated by Django 4.1.5 on 2023-01-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0005_fotografia_date_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='photo',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
